# -*- coding: utf-8 -*-
"""MAS_fast.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KEzR2gAMSCKlZ1HV0Tl46xb1ane3Lxq_
"""

from random import random, randint, shuffle
from math import sqrt, sin, cos
import json
import sys

NUMBER_ACTIVE_CARS = int(3271000 * 0.235 * 0.3)

STATIONS = None
VERTEXES = None
GRAPH = None
CARS = None
VERTEX_DICT = dict()

class Vertex:
    def __init__(self, id, is_station, location):
        self.id = id
        self.is_station = is_station
        self.location = location
        self.sold_gasoline = 0
        self.number_visited = 0
        self.number_stopped = 0
        self.number_cars = 0


    def get_id(self):
        return self.id


    def get_is_station(self):
        return self.is_station


    def get_location(self):
        return self.location


class Car:
    def __init__(self, capacity, spending, vertex, velocity_coeff):
        self.capacity = capacity
        self.current_capacity = capacity * max(0.2, random())
        self.spending = spending
        self.vertex = vertex
        self.velocity_coeff = velocity_coeff
        self.local_time = 0
        self.time_attend = 0
        self.active = False


    def get_vertex(self):
        return self.vertex


    def get_capacity(self):
        return self.capacity


    def get_spending(self):
        return self.spending


    def get_velocity_coeff(self):
        return self.velocity_coeff


    def _possibility_refuel(self, percentage_fuel):
        return (1 - (1 - percentage_fuel) ** 4)


    def next_direction(self, neighbours):
        if not self.active:
            if random() > 0.99:
                self.active = True
                if self.current_capacity < self.capacity * 0.2:
                    self.current_capacity = self.capacity * min(random(), 0.3)
        if not self.active:
            pass
        if self.time_attend <= self.local_time:
            non_stations = []
            for neighbour in neighbours:
                if neighbour.is_station:
                    dist = sqrt((self.vertex.location[0] - neighbour.location[0]) ** 2
                                + (self.vertex.location[1] - neighbour.location[1]) ** 2)
                    if self.current_capacity > self.spending * dist:
                        p_refuel = self._possibility_refuel(float(self.current_capacity) / float(self.capacity))
                        if random() < p_refuel:
                            self.time_attend = dist * self.velocity_coeff + randint(1, 5) * randint(1, 5) * randint(0, 5)
                            self.vertex.number_cars -= 1
                            neighbour.number_cars += 1
                            neighbour.sold_gasoline += (self.capacity - self.current_capacity)
                            self.current_capacity = self.capacity
                            self.vertex = neighbour
                            self.vertex.number_visited += 1
                            self.vertex.number_stopped += 1
                            if random() > 0.4:
                                self.active = False
                else:
                    non_stations.append(neighbour)
            non_stations = neighbours
            if len(non_stations) == 0:
                self.active = False
            shuffle(non_stations)
            good_pos = 0
            for neighbour in non_stations:
                dist = sqrt((self.vertex.location[0] - neighbour.location[0]) ** 2
                                + (self.vertex.location[1] - neighbour.location[1]) ** 2)
                if self.current_capacity > self.spending * dist:
                    self.current_capacity -= self.spending * dist
                    self.vertex.number_cars -= 1
                    neighbour.number_cars += 1
                    self.vertex = neighbour
                    self.vertex.number_visited += 1
                    if random() > 0.95:
                        self.active = False
        else:
            pass
        self.local_time += 1


def load_stations(path):
    with open(path) as f:
        data = json.load(f)
    return [[i[0] * 78.7, i[1] * 111.13] for i in data['stations']] # тупой перевод в прямоугольные координаты


def build_vertexes():
    global GRAPH
    GRAPH = dict()
    vertexes = []
    counter = 0
    for i in STATIONS:
        vertexes.append(Vertex(counter, True, i))
        VERTEX_DICT[vertexes[-1]] = counter
        counter += 1
    with open('roads.txt', 'r') as f:
        x = f.readlines()
        for j in x:
            w = j.split(' ')
            for i in range(0, len(w), 2):
                if i + 1 >= len(j) or j[i] == '.' or j[i + 1] == '.':
                    break
                if Vertex(counter, False, [float(j[i + 1]), float(j[i])]) not in VERTEX_DICT.keys():
                    vertexes.append(Vertex(counter, False, [float(j[i + 1]) * 78.7, float(j[i]) * 111.13]))
                    VERTEX_DICT[vertexes[-1]] = counter
                    counter += 1
                if i > 0:
                    if vertexes[-1] not in GRAPH.keys():
                        GRAPH[vertexes[-1]] = []
                    GRAPH[vertexes[-1]].append(vertexes[-2])
                    if vertexes[-2] not in GRAPH.keys():
                        GRAPH[vertexes[-2]] = []
                    GRAPH[vertexes[-2]].append(vertexes[-1])
    for i in range(0, len(STATIONS)):
        for j in range(len(STATIONS), len(vertexes)):
            if vertexes[i] not in GRAPH.keys():
                GRAPH[vertexes[i]] = []
            if vertexes[j] not in GRAPH.keys():
                GRAPH[vertexes[j]] = []
            GRAPH[vertexes[i]].append(vertexes[j])
            GRAPH[vertexes[j]].append(vertexes[i])
    return vertexes


def build_cars():
    return [Car(100 * max(0.6, random()), 0.2 * max(0.3, random()), VERTEXES[randint(0, len(VERTEXES) - 1)], 0.9 + random() * 0.1) for i in range(NUMBER_ACTIVE_CARS)]


def export_data():
    data = dict()
    data['stations'] = []
    for station in VERTEXES:
        if station.is_station:
            st = dict()
            st['loc'] = station.location
            st['number_visitors'] = station.number_visited
            st['number_stopped'] = station.number_stopped
            st['sold_gasoline'] = station.sold_gasoline
            data['stations'].append(st)
    json_object = json.dumps(data, indent=4)
    with open("stats.json", "w") as outfile:
        outfile.write(json_object)


def main():
    if len(sys.argv) != 2:
        print('invalid number of arguments')
        raise 1
    global STATIONS, VERTEXES, GRAPH, CARS
    STATIONS = load_stations(sys.argv[1])
    VERTEXES = build_vertexes()
    CARS = build_cars()

    for i in range(1440):
        for j in range(len(CARS)):
            CARS[j].next_direction(GRAPH[CARS[j].get_vertex()])

    for i in VERTEXES:
        if i.get_is_station():
            print(i.location, i.number_visited, i.number_stopped, i.sold_gasoline)

    export_data()


if __name__ == '__main__':
    main()